security:
  user:
    password: none
  
logging:
  level:
    org:
      
      hibernate:  DEBUG
      springframework:
        web:  DEBUG
        security: DEBUG
             
facebook:
  appKey: 1896232807325142
  appSecret: 64096be669990079e7120465bc65de01
  
token:
  secret: willremvoeit
  
support:
  email: xplusyz@yahoo.com
  from: noreply_xplusyz@xplusyz.com
  
---

spring:
  profiles: default
  datasource:
    url: jdbc:postgresql://localhost:5432/local-idp-xplusyz-db
    username: idpuser
    password: test123!
  jpa:
    hibernate:
      ddl-auto: validate
    showSql: true 
  queries:
    users-query: select email, password, enabled from users where email=?
    roles-query: select u.email, r.role from users u inner join user_roles ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?
    
  mail:
    host: smtp.sendgrid.net
    port: 465
    protocol: smtps
    username: azure_82d63a8199cb145e13ffd8dffcf3b801@azure.com
    password: test123!
    properties:
      mail:
        transport:
          protocol: smtps
      properties:
        mail:
          smtps:
            ssl:
              enable: true  
            auth: true  
            #starttls:
              #enable: true
            timeout: 2000

server:
  port: 9999
  contextPath: /uaa
  
base:
  protocol: http://
  host: localhost:8080
  #port: 8080


---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/local-idp-xplusyz-db
    username: idpuser
    password: test123!
  jpa:
    hibernate:
      ddl-auto: validate
    showSql: true 
  queries:
    users-query: select email, password, enabled from users where email=?
    roles-query: select u.email, r.role from users u inner join user_roles ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?
    
  mail:
    host: smtp.sendgrid.net
    port: 465
    protocol: smtps
    username: azure_82d63a8199cb145e13ffd8dffcf3b801@azure.com
    password: test123!
    properties:
      mail:
        transport:
          protocol: smtps
      properties:
        mail:
          smtps:
            ssl:
              enable: true
            auth: true  
            #starttls:
              #enable: true
            timeout: 2000 

server:
  port: 9999
  contextPath: /uaa

base:
  protocol: http://
  host: localhost:8080
  #port: 8080
    
---

spring:
  profiles: heroku 
  #datasource:
    #url: ${JDBC_DATABASE_URL}
    #username: ${JDBC_DATABASE_USERNAME}
    #password: ${JDBC_DATABASE_PASSWORD}   
  jpa:
    hibernate:
      ddl-auto: create
    showSql: true 
  queries:
    users-query: select email, password, enabled from users where email=?
    roles-query: select u.email, r.role from users u inner join user_roles ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?

  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 2525
    protocol: smtps
    username: AKIAJIKXZAQFFJDXI4VQ
    password: 
    properties:
      mail:
        transport:
          protocol: smtps
      properties:
        mail:
          smtps:
            auth: true  
            starttls:
              enable: true
            timeout: 2000
            
server:
  port: ${PORT:9999}
  contextPath: /uaa

base:
  protocol: https://
  host: dev-xplusyz.azurewebsites.net
  #port:  